networks:
  payment-processor:
    external: true
  app-network:
    driver: bridge

services:
  # redis para cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: payment-db
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "80MB"

  # FastAPI Application Instance 1
  app1: &api
    build: .
    container_name: payment-app1
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/payments
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - INSTANCE_NAME=app1
    expose:
      - "9999"
    depends_on:
      - postgres
      - redis
    networks:
      - app-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "120MB"

  # FastAPI Application Instance 2
  app2:
    <<: *api
    container_name: payment-app2
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/payments
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - INSTANCE_NAME=app2

  # Nginx Load Balancer
  nginx:
    image: nginx:alpine
    container_name: payment-nginx
    ports:
      - "9999:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    networks:
      - app-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "10MB"

volumes:
  redis_data:
  postgres_data:
  pgadmin_data:
